Fix most vulnerabilities
The prometheus stuff is still stubbornly there

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,8 +2,41 @@
 
 set -euo pipefail
 
+CALLED="${BASH_ARGV0:-${BASH_SOURCE:-${0}}}"
+SCRIPT="$(readlink -f "${CALLED}")"
+BASEDIR="$(dirname "${SCRIPT}")"
+SCRIPT="$(basename "${SCRIPT}")"
+
+timestamp()
+{
+	date -Ins -u
+}
+
+say()
+{
+	local SUFFIX=""
+	[ -v PARALLEL_ID ] && SUFFIX="|${!PARALLEL_ID}"
+	echo -e "$(timestamp) [${$}${SUFFIX}]: ${@}"
+}
+
+ok()
+{
+	say "✅ ${@}"
+}
+
+err()
+{
+	say "❌ ${@}"
+}
+
+fail()
+{
+	err "${@}"
+	exit ${EXIT_CODE:-1}
+}
+
 if [ ${#} -lt 2 ] ; then
-	echo "usage: ${0} REPOSITORY VERSION [ fix-1 fix-2 fix-3 ... fix-N ]"
+	echo "usage: ${CALLED} REPOSITORY VERSION [ fix-1 fix-2 fix-3 ... fix-N ]"
 	exit 1
 fi
 
@@ -11,18 +44,46 @@ REPO="${1}"
 VERSION="${2}"
 shift 2
 
-echo "Building ${REPO} version [${VERSION}]"
+say "Building ${REPO} version [${VERSION}]"
 mkdir -p /src
-DIR="$(mktemp -d --tmpdir=/src)"
+DIR="$(mktemp -d --tmpdir=/src 2>&1)" || fail "Failed to create a temporary directory (rc=${?}): ${DIR}"
 
 cd "${DIR}"
-git clone "${REPO}" . --branch "RELEASE.${VERSION}"
+REF="RELEASE.${VERSION}"
+OUT="$(git clone "${REPO}" . --branch "${REF}" 2>&1)" || fail "Failed to clone the repository [${REPO}] on version [${REF}] (rc=${?}): ${OUT}"
 
+FIXES_FILE="${BASEDIR}/build-fixes.yaml"
+if [ -f "${FIXES_FILE}" ] && [ -r "${FIXES_FILE}" ] ; then
+	FIXES_JSON="$("${BASEDIR}/yaml2json" < "${FIXES_FILE}" 2>&1)" || fail "Failed to convert the fix file [${FIXES_FILE}] to JSON (rc=${?}): ${FIXES_JSON}"
+else
+	FIXES_JSON="{}"
+fi
+
+POS=0
 for FIX in "${@}" ; do
-	echo "Applying fix [${FIX}] ..."
-	go get -u "${FIX}"
+	[ -n "${FIX}" ] || fail "Invalid empty fix on position ${POS}"
+
+	FIXES="$(jq -r --arg FIX "${FIX}" '.[$FIX]' <<< "${FIXES_JSON}" 2>&1)" || fail "No fix set named [${FIX}] was found in the configuration (rc=${?}): ${FIXES}"
+	say "Applying fix set [${FIX}] ..."
+
+	PATCHES="$(jq -r 'to_entries[] | "\(.key)@\(.value)"' <<< "${FIXES}" 2>&1)" || fail "Failed to read the patch list for fix set [${FIX}] (rc=${?}): ${PATCHES}"
+	[ -n "${PATCHES}" ] || continue
+	say "Found the following patches for [${FIX}]:\n${PATCHES}"
+
+	while read PATCH ; do
+		[ -n "${PATCH}" ] || continue
+		say "Applying patch [${PATCH}] ..."
+		OUT="$(go get -u "${PATCH}" 2>&1)" || fail "Failed to apply the patch [${PATCH}] from fix set [${FIX}] (rc=${?}):\n${OUT}"
+		ok "Patch applied!"
+	done <<< "${PATCHES}"
+	(( ++POS ))
 done
 
-go mod tidy
+say "Go Tidy"
+OUT="$(go mod tidy 2>&1)" || fail "Failed to tidy up the code (rc=${?}):\n${OUT}"
 
-exec go install -v -ldflags "$(go run buildscripts/gen-ldflags.go "${VERSION}")"
+say "Computing linker flags..."
+LDFLAGS="$(go run buildscripts/gen-ldflags.go "${VERSION}" 2>&1)" || fail "Failed to compute the version flags (rc=${?}): ${LDFLAGS}"
+
+say "Building with the linker flags [${LDFLAGS}]..."
+exec go install -v -ldflags "${LDFLAGS}"
